package io.kroom.app.model


data class Album(val id: Int,
                 val title: String,
                 val link: String,
                 val cover: String,
                 val coverSmall: String,
                 val coverMedium: String,
                 val coverBig: String,
                 val coverXl: String,
                 val genreId: Int,
                 val genre: Genre,
                 val label: String,
                 val nbTracks: Int,
                 val duration: Int,
                 val fans: Int,
                 val rating: Int,
                 val releaseDate: String,
                 val recordType: String,
                 val available: Boolean,
                 val tracklist: String,
                 val explicitLyrics: Boolean,
                 val explicitContentLyrics: Int,
                 val explicitContentCover: Int,
                 val contributors: Artist,
                 val artistId: Int,
                 val artist: Artist,
                 val tracks: Track)